site_name: docs.snawf.my.id
site_description: Official documentation for snawf.my.id
site_url: https://docs.snawf.my.id
repo_url: https://github.com/onthecouch/docs.snawf.my.id
repo_name: docs.snawf.my.id

nav:
  - Home: index.md
  - Homelab:
      - Initial Setup: homelab/installation.md
      - Post Install: homelab/post-install.md
      - AdGuard Home: homelab/adguard-home.md
      - Hardening AdGuard: homelab/hardening-adguard.md
      - Nginx Proxy Manager: homelab/nmp.md
      - Cloudflared: homelab/cloudflared.md
  - Windows:
      - Customizing Powershell: windows/custom-powershell.md
      - HP DL 160 HDD Driver: windows/dl160-gen10-storage-drivers.md

theme:
  name: material
  language: en
  favicon: assets/hdfav60.png
  logo: assets/hdfav60.png

  font:
    text: "Work Sans"
    code: "JetBrains Mono"

  palette:
    scheme: slate
    primary: black
    accent: deep orange

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy       # copy-to-clipboard
    - content.code.line       # line selection toggle
    - navigation.sections
    - navigation.expand

  hide:
    - toc

plugins:
  - search

markdown_extensions:
  - admonition
  - fenced_code
  - codehilite:
      guess_lang: false
      use_pygments: true
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true           # show line numbers
      linenums_style: table
      anchor_linenums: true    # enable line selection toggle

extra_css:
  - stylesheets/extra.css

extra:
  generator: false

copyright:
  Copyright © 2019–2026 snawf.my.id
