site_name: docs.snawf.my.id
site_description: Official documentation for snawf.my.id
site_url: https://docs.snawf.my.id
repo_url: https://github.com/onthecouch/docs.snawf.my.id
repo_name: docs.snawf.my.id

nav:
  - Home: index.md

  - Homelab:
      - Overview: homelab/index.md

      - Proxmox:
          - Initial Setup: homelab/01.installation.md
          - Post Install: homelab/02.post-install.md

      - Networking & Services:
          - AdGuard Home: homelab/03.adguard-home.md
          - Nginx Proxy Manager: homelab/04.nmp.md
          - Cloudflared: homelab/05.cloudflared.md
          - Homepage: homelab/06.dashboard.md
          - Media Server: homelab/07.media-stack.md
  - Windows:
      - Customizing Powershell: windows/custom-powershell.md
      - HP DL 160 HDD Driver: windows/dl160-gen10-storage-drivers.md

theme:
  name: material
  language: en
  favicon: assets/hdfav60.png
  logo: assets/hdfav60.png

  font:
    text: "Work Sans"
    code: "JetBrains Mono"

  palette:
    scheme: slate
    primary: black
    accent: deep orange

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy       # copy-to-clipboard
    - content.code.select
    - navigation.sections
    - navigation.expand
    - navigation.footer


plugins:
  - search

markdown_extensions:
  - admonition
  - fenced_code
  - codehilite:
      guess_lang: false
      use_pygments: true
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      line_spans: __span          
      pygments_lang_class: true
      anchor_linenums: true 
  

extra_css:
  - stylesheets/extra.css

extra:
  generator: false

copyright:
  Copyright © 2019–2026 snawf.my.id
